config/routes.rb
Rails.application.routes.draw do
  root to: 'categories#index'
  resources :categories do
    resources :companies, except: [:index]
  end

end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :name, presence: true
  has_many :companies
  
end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :name, presence: true
  belongs_to :category
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category successfully added!"
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:notice] = "Category successfully updated!"
      redirect_to category_path(@category)
    else
      render :edit
    end
  end

  def destroy
    category = Category.find(params[:id])
    category.destroy
    flash[:notice] = "Category successfully eliminated."
    redirect_to categories_path
  end

private

  def category_params
    params.require(:category).permit(:name)
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def new
    @category = Category.find(params[:category_id])
    @company = @category.companies.new
  end

  def create
    @category = Category.find(params[:category_id])
    @company = @category.companies.new(company_params)
    if @company.save
      flash[:notice] = "Company successfully added!"
      redirect_to category_path(@category)
    else
      render :new
    end
  end

  def show
    @category = Category.find(params[:category_id])
    @company = Company.find(params[:id])
  end

  def edit
    @category = Category.find(params[:category_id])
    @company = Company.find(params[:id])
  end

  def update
    @category = Category.find(params[:category_id])
    @company = Company.find(params[:id])
    if @company.update(company_params)
      flash[:notice] = "Company successfully updated."
      redirect_to category_company_path(@category, @company)
    else
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:category_id])
    company = Company.find(params[:id])
    company.destroy
    flash[:notice] = "Company successfully deleted."
    redirect_to category_path(@category)
  end


private
  def company_params
    params.require(:company).permit(:name, :address, :website, :phone, :hours)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<%= render "layouts/errors", object: @category %>

<%= form_for @category do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= render 'form' %>

app/views/categories/index.html.erb
<h1>Categories</h1>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category_path(category) %></li>
  <% end %>
</ul>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form' %>

app/views/categories/show.html.erb
<nav class="sub-nav">
  <ul>
    <li class="navbar-name"><%= @category.name %></li>
    <li><%= link_to "Add Company", new_category_company_path(@category)%></li>
    <li><%= link_to "Edit", edit_category_path %></li>
    <li><%= link_to "Delete", category_path(@category), data: {confirm: "are you sure?", method: "delete"} %></li>
  </ul>
</nav>

<% if @category.companies.any? %>
  <h4>Companies:</h4>
    <ul>
      <% @category.companies.each do |company| %>
        <li><%= link_to company.name, category_company_path(@category, company) %></li>
      <% end %>
    </ul>
<% else %>
  <p>No companies.</p>
<% end %>

app/views/companies/_form.html.erb
<%= render "layouts/errors", object: @company %>

<%= form_for [@category, @company], :html => { :class => "form-horizontal" } do |f| %>
  <div class="form-group">
    <%= f.label :name, {class: "col-md-2"} %>
    <%= f.text_field :name, {class: "col-md-8"}%>
  </div>
  <div class="form-group">
    <%= f.label :address, {class: "col-md-2"} %>
    <%= f.text_field :address, {class: "col-md-8"} %>
  </div>
  <div class="form-group">
    <%= f.label :website, {class: "col-md-2"} %>
    <%= f.text_field :website, {class: "col-md-8"} %>
  </div>
  <div class="form-group">
    <%= f.label :hours, {class: "col-md-2"} %>
    <%= f.text_field :hours, {class: "col-md-8"} %>
  </div>
  <div class="form-group">
    <%= f.label :phone, {class: "col-md-2"} %>
    <%= f.text_field :phone, {class: "col-md-8"} %>
  </div>
  <%= f.submit class: "col-md-offset-2 company-button" %>
<% end %>

app/views/companies/edit.html.erb
<h1>Edit Company</h1>

<%= render 'form' %>

app/views/companies/new.html.erb
<h2>New company for <%= @category.name %></h2>

<%= render 'form' %>

app/views/companies/show.html.erb
<nav class="sub-nav">
  <ul>
    <li class="navbar-name"><%= @company.name %></li>
    <li><%= link_to "Back", category_path(@category) %></li>
    <li><%= link_to "Edit", edit_category_company_path(@category, @company) %></li>
    <li><%= link_to "Delete", category_company_path(@category, @company), data: {confirm: "are you sure?", method: "delete"} %></li>
  </ul>
</nav>
<p><%= @company.address %></p>
<p><%= @company.phone %></p>
<p><%= @company.website %></p>
<p><%= @company.hours %></p>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Yellow Pages</title>
  <link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css" rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <nav>
      <ul>
        <li><%= link_to "Home", categories_path %></li>
        <li><%= link_to "Add Category", new_category_path %></li>
      </ul>
    </nav>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </div>

</body>
</html>